#!/usr/bin/env python3
"""Install and validate Harness-dev Agent Kit assets.

Local methodology skills live under agent-kit/skills/skills/<name>.
Client trees (.cursor / .claude / .codex / .agents) are generated by install
and must not be committed — see .gitignore.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[2]
AGENT_KIT = ROOT / "agent-kit"
MANIFEST_PATH = AGENT_KIT / "manifest.json"
CONSTRAINTS_PATH = AGENT_KIT / "install" / "constraints.json"
MCP_PATH = AGENT_KIT / "mcp" / "servers.json"
HOOKS_PATH = AGENT_KIT / "hooks" / "hooks.json"
CLIENT_HOOKS_DIR = AGENT_KIT / "hooks" / "clients"
EXTERNAL_SKILLS_PATH = AGENT_KIT / "external-skills.json"
EXTERNAL_SKILLS_LOCK_PATH = AGENT_KIT / "external-skills-lock.json"
OPTIONAL_PLUGINS_PATH = AGENT_KIT / "optional-plugins.json"
OPTIONAL_PLUGINS_LOCK_PATH = AGENT_KIT / "optional-plugins-lock.json"
AGENT_PROFILE_CLI = AGENT_KIT / "profile" / "agent-profile.mjs"
DEFAULT_PROFILE = "harness-dev"
CLIENT_CHOICES = ("cursor", "cursor-cli", "claude", "codex", "codex-native")
CORE_SKILL_DESCRIPTIONS = {
    "test-driven-development": (
        "Use when maintained reproducible behavior can be specified by a failing automated test; "
        "skip pure docs, research, configuration-only edits, and throwaway probes."
    ),
    "systematic-debugging": (
        "Use for failing tests, regressions, crashes, or unexpected behavior that need root-cause "
        "diagnosis; skip when the cause and requested fix are already known."
    ),
    "verification-before-completion": (
        "Use immediately before claiming fixed, complete, or passing, or before commit and PR, to "
        "collect fresh command evidence; skip ordinary progress updates."
    ),
    "requesting-code-review": (
        "Use after substantial implementation when an explicit adversarial review is needed before "
        "merge; skip routine self-checks and non-code answers."
    ),
    "receiving-code-review": (
        "Use when concrete review feedback has been received and must be verified before changes; "
        "skip when no reviewer feedback is present."
    ),
}


def load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def ensure_parent(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)


def write_json(path: Path, data: dict[str, Any]) -> None:
    ensure_parent(path)
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def write_text(path: Path, text: str) -> None:
    ensure_parent(path)
    if not text.endswith("\n"):
        text += "\n"
    path.write_text(text, encoding="utf-8")


def run_agent_profile(*args: str) -> dict[str, Any]:
    proc = subprocess.run(
        ["node", str(AGENT_PROFILE_CLI), *args],
        cwd=ROOT,
        text=True,
        capture_output=True,
    )
    if proc.returncode != 0:
        raise ValueError(proc.stderr.strip() or proc.stdout.strip() or "agent profile command failed")
    try:
        return json.loads(proc.stdout)
    except json.JSONDecodeError as exc:
        raise ValueError(f"agent profile returned invalid JSON: {exc}") from exc


def prepare_agent_profile(
    output_root: Path,
    client: str,
    *,
    write_outputs: bool,
    process_scaffold: str | None,
) -> tuple[dict[str, Any], str | None]:
    root_args = ["--root", str(output_root)]
    if process_scaffold is not None:
        run_agent_profile("set", "process_scaffold", process_scaffold, *root_args)
    runtime_hash: str | None = None
    if write_outputs:
        exported = run_agent_profile("export", *root_args, "--client", client)
        runtime_hash = str(exported["runtime_hash"])
    profile = run_agent_profile("show", *root_args, "--json")
    return profile, runtime_hash


def parse_frontmatter(path: Path) -> dict[str, str]:
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        return {}
    block = text.split("---", 2)[1]
    data: dict[str, str] = {}
    current_key: str | None = None
    current_lines: list[str] = []

    def flush_block() -> None:
        nonlocal current_key, current_lines
        if current_key is not None:
            data[current_key] = " ".join(line.strip() for line in current_lines).strip()
            current_key = None
            current_lines = []

    for line in block.splitlines():
        if not line.strip():
            continue
        if current_key and line.startswith((" ", "\t")):
            current_lines.append(line)
            continue
        flush_block()
        if ":" not in line or line.startswith((" ", "\t")):
            continue
        key, raw_value = line.split(":", 1)
        key = key.strip()
        value = raw_value.strip()
        if value in {">", ">-", "|", "|-"}:
            current_key = key
            current_lines = []
        else:
            data[key] = value.strip().strip('"').strip("'")
    flush_block()
    return data


def local_skills_root(constraints: dict[str, Any] | None = None) -> Path:
    cfg = constraints if constraints is not None else load_json(CONSTRAINTS_PATH)
    sub = str(cfg.get("local_skills_subdir", "skills/skills"))
    return AGENT_KIT / sub


def profile_skills(manifest: dict[str, Any], profile: str) -> list[str]:
    try:
        skills = manifest["profiles"][profile]["skills"]
    except KeyError as exc:
        raise ValueError(f"unknown profile: {profile}") from exc
    return list(skills)


def profile_commands(manifest: dict[str, Any], profile: str) -> list[str]:
    try:
        commands = manifest["profiles"][profile].get("commands", [])
    except KeyError as exc:
        raise ValueError(f"unknown profile: {profile}") from exc
    return list(commands)


def profile_hooks(manifest: dict[str, Any], profile: str) -> list[str]:
    try:
        hooks = manifest["profiles"][profile].get("hooks", [])
    except KeyError as exc:
        raise ValueError(f"unknown profile: {profile}") from exc
    return list(hooks)


def profile_external_skills(profile: str) -> list[dict[str, Any]]:
    if not EXTERNAL_SKILLS_PATH.exists():
        return []
    config = load_json(EXTERNAL_SKILLS_PATH)
    try:
        external_skills = config["profiles"].get(profile, {}).get("skills", [])
    except KeyError as exc:
        raise ValueError(f"invalid external skill config: {EXTERNAL_SKILLS_PATH}") from exc
    return list(external_skills)


def locked_external_skills(profile: str) -> list[dict[str, Any]]:
    declarations = profile_external_skills(profile)
    locks = load_json(EXTERNAL_SKILLS_LOCK_PATH).get("skills", {}) if EXTERNAL_SKILLS_LOCK_PATH.exists() else {}
    resolved: list[dict[str, Any]] = []
    for declaration in declarations:
        name = str(declaration.get("name", ""))
        locked = locks.get(name, {})
        merged = {**declaration, **locked, "name": name}
        resolved.append(merged)
    return resolved


def optional_plugin_declarations() -> dict[str, dict[str, Any]]:
    if not OPTIONAL_PLUGINS_PATH.exists():
        return {}
    return load_json(OPTIONAL_PLUGINS_PATH).get("plugins", {})


def locked_optional_plugins(names: list[str]) -> list[dict[str, Any]]:
    declarations = optional_plugin_declarations()
    locks = load_json(OPTIONAL_PLUGINS_LOCK_PATH).get("plugins", {}) if OPTIONAL_PLUGINS_LOCK_PATH.exists() else {}
    resolved: list[dict[str, Any]] = []
    seen: set[str] = set()
    for name in names:
        if name in seen:
            continue
        seen.add(name)
        declaration = declarations.get(name)
        if not isinstance(declaration, dict):
            raise ValueError(f"{name}: unknown optional plugin")
        locked = locks.get(name)
        if not isinstance(locked, dict):
            raise ValueError(f"{name}: optional plugin missing from agent-kit/optional-plugins-lock.json")
        merged = {**declaration, **locked, "name": name}
        resolved.append(merged)
    return resolved


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def sha256_files(paths: list[Path]) -> str:
    digest = hashlib.sha256()
    for path in paths:
        digest.update(path.read_bytes())
    return digest.hexdigest()


def count_tokens(text: str, model: str) -> tuple[int, str]:
    """Count discovery tokens; fall back to unicode codepoints when tiktoken/network unavailable."""
    try:
        import tiktoken
    except ModuleNotFoundError:
        return len(text), "unicode-codepoint"
    try:
        try:
            encoding = tiktoken.encoding_for_model(model)
            tokenizer = model
        except KeyError:
            encoding = tiktoken.get_encoding("o200k_base")
            tokenizer = "o200k_base"
        return len(encoding.encode(text)), tokenizer
    except Exception:
        # Offline / sandboxed environments cannot fetch encoding tables.
        return len(text), "unicode-codepoint"


def validate(profile: str) -> dict[str, Any]:
    manifest = load_json(MANIFEST_PATH)
    constraints = load_json(CONSTRAINTS_PATH)
    name_re = re.compile(constraints["skill_name_pattern"])
    max_desc = int(constraints["skill_description_max_chars"])
    tokenizer_model = str(constraints["skill_discovery_tokenizer_model"])
    context_window_tokens = int(constraints["skill_discovery_context_window_tokens"])
    budget_fraction = float(constraints["skill_discovery_budget_fraction"])
    budget_tokens = int(context_window_tokens * budget_fraction)
    warning_threshold_tokens = int(constraints["skill_discovery_warning_threshold_tokens"])
    error_threshold_tokens = int(constraints["skill_discovery_error_threshold_tokens"])
    skills = profile_skills(manifest, profile)
    commands = profile_commands(manifest, profile)
    hook_profiles = profile_hooks(manifest, profile)
    external_skills = profile_external_skills(profile)
    hooks_cfg = load_json(HOOKS_PATH) if HOOKS_PATH.exists() else {"hooks": {}}
    hooks = hooks_cfg.get("hooks", {})
    skills_lock = load_json(EXTERNAL_SKILLS_LOCK_PATH) if EXTERNAL_SKILLS_LOCK_PATH.exists() else {"skills": {}}
    locked_skills = skills_lock.get("skills", {})
    skills_root = local_skills_root(constraints)

    errors: list[str] = []
    warnings: list[str] = []
    discovery_chars = 0
    discovery_entries: list[str] = []
    for name in skills:
        skill_dir = skills_root / name
        skill_md = skill_dir / "SKILL.md"
        if not name_re.match(name):
            errors.append(f"{name}: invalid skill directory name")
        if not skill_md.exists():
            errors.append(f"{name}: missing SKILL.md")
            continue
        frontmatter = parse_frontmatter(skill_md)
        fm_name = frontmatter.get("name")
        description = frontmatter.get("description", "")
        if fm_name != name:
            errors.append(f"{name}: frontmatter name must match directory")
        if not description:
            errors.append(f"{name}: description is required")
        if len(description) > max_desc:
            errors.append(f"{name}: description exceeds {max_desc} chars")
        discovery_chars += len(name) + len(description)
        discovery_entries.append(f"{name}: {description}")
    discovery_text = "\n".join(discovery_entries)
    discovery_tokens, tokenizer = count_tokens(discovery_text, tokenizer_model)
    if discovery_tokens > error_threshold_tokens:
        errors.append(
            f"profile {profile} discovery metadata is {discovery_tokens} tokens; "
            f"error threshold is {error_threshold_tokens} tokens"
        )
    elif discovery_tokens > warning_threshold_tokens:
        warnings.append(
            f"profile {profile} discovery metadata is {discovery_tokens} tokens; "
            f"warning threshold is {warning_threshold_tokens} tokens"
        )

    for name in commands:
        command_path = AGENT_KIT / "commands" / f"{name}.md"
        if not name_re.match(name):
            errors.append(f"{name}: invalid command name")
        if not command_path.exists():
            errors.append(f"{name}: missing command source")

    if hook_profiles:
        if not isinstance(hooks, dict) or not hooks:
            errors.append(f"profile {profile} declares hooks but agent-kit/hooks/hooks.json is empty")
        for hook_name in hook_profiles:
            if hook_name == "default":
                continue
            if hook_name not in hooks:
                errors.append(f"{hook_name}: hook referenced by profile but missing from hooks.json")

    external_skill_names: list[str] = []
    for skill_cfg in external_skills:
        if not isinstance(skill_cfg, dict):
            errors.append("external skill config must be an object")
            continue
        name = str(skill_cfg.get("name", ""))
        external_skill_names.append(name)
        if not name_re.match(name):
            errors.append(f"{name}: invalid external skill name")
        if name in skills:
            errors.append(f"{name}: external skill must not also be declared as local profile skill")
        for key in ("source", "sourceType", "path"):
            if not skill_cfg.get(key):
                errors.append(f"{name}: external skill {key} is required")
        locked = locked_skills.get(name)
        if not isinstance(locked, dict):
            errors.append(f"{name}: external skill missing from agent-kit/external-skills-lock.json")
            continue
        for key in ("source", "sourceType", "path"):
            if locked.get(key) != skill_cfg.get(key):
                errors.append(f"{name}: external-skills-lock.json {key} must match external-skills.json")
        if not re.fullmatch(r"[0-9a-f]{40}", str(locked.get("ref", ""))):
            errors.append(f"{name}: external-skills-lock.json ref must be a 40-char git commit")
        if not re.fullmatch(r"[0-9a-f]{64}", str(locked.get("computedHash", ""))):
            errors.append(f"{name}: external-skills-lock.json computedHash must be a sha256 hex digest")

    optional_plugins_cfg = optional_plugin_declarations()
    optional_plugins_lock = (
        load_json(OPTIONAL_PLUGINS_LOCK_PATH).get("plugins", {})
        if OPTIONAL_PLUGINS_LOCK_PATH.exists()
        else {}
    )
    for name, plugin_cfg in optional_plugins_cfg.items():
        if not name_re.match(name):
            errors.append(f"{name}: invalid optional plugin name")
        if not isinstance(plugin_cfg, dict):
            errors.append(f"{name}: optional plugin config must be an object")
            continue
        for key in ("source", "sourceType", "path", "clients"):
            if not plugin_cfg.get(key):
                errors.append(f"{name}: optional plugin {key} is required")
        if plugin_cfg.get("sourceType") not in {"github", "git"}:
            errors.append(f"{name}: unsupported optional plugin sourceType {plugin_cfg.get('sourceType')!r}")
        locked = optional_plugins_lock.get(name)
        if not isinstance(locked, dict):
            errors.append(f"{name}: optional plugin missing from agent-kit/optional-plugins-lock.json")
            continue
        for key in ("source", "sourceType", "path"):
            if locked.get(key) != plugin_cfg.get(key):
                errors.append(f"{name}: optional-plugins-lock.json {key} must match optional-plugins.json")
        if not re.fullmatch(r"[0-9a-f]{40}", str(locked.get("ref", ""))):
            errors.append(f"{name}: optional-plugins-lock.json ref must be a 40-char git commit")

    return {
        "profile": profile,
        "skills": skills,
        "external_skills": sorted(external_skill_names),
        "optional_plugins": sorted(optional_plugins_cfg),
        "commands": commands,
        "hooks": sorted(hook_profiles),
        "errors": errors,
        "warnings": warnings,
        "skill_description_max_chars": max_desc,
        "skill_discovery_tokenizer_model": tokenizer_model,
        "skill_discovery_tokenizer": tokenizer,
        "skill_discovery_context_window_tokens": context_window_tokens,
        "skill_discovery_budget_fraction": budget_fraction,
        "skill_discovery_budget_tokens": budget_tokens,
        "skill_discovery_warning_threshold_tokens": warning_threshold_tokens,
        "skill_discovery_error_threshold_tokens": error_threshold_tokens,
        "skill_discovery_tokens": discovery_tokens,
        "skill_discovery_chars": discovery_chars,
    }


def install_client_surface(
    client: str,
    client_cfg: dict[str, Any],
    output_root: Path,
    targets: list[str],
    *,
    write_outputs: bool,
) -> None:
    """Write client hooks/settings from agent-kit/hooks/clients/ (install SSOT)."""
    if client in {"cursor", "cursor-cli"}:
        hooks_rel = client_cfg["hooks_path"]
        targets.append(hooks_rel)
        if write_outputs:
            src = CLIENT_HOOKS_DIR / "cursor.hooks.json"
            if not src.is_file():
                raise FileNotFoundError(f"missing client hook template: {src}")
            write_json(output_root / hooks_rel, load_json(src))
        return
    if client == "claude":
        settings_rel = client_cfg["settings_path"]
        targets.append(settings_rel)
        if write_outputs:
            src = CLIENT_HOOKS_DIR / "claude.settings.json"
            if not src.is_file():
                raise FileNotFoundError(f"missing client settings template: {src}")
            write_json(output_root / settings_rel, load_json(src))
        return
    if client == "codex":
        config_rel = client_cfg["config_path"]
        hooks_rel = client_cfg["hooks_path"]
        targets.extend([config_rel, hooks_rel])
        if write_outputs:
            cfg_src = CLIENT_HOOKS_DIR / "codex.config.toml"
            hooks_src = CLIENT_HOOKS_DIR / "codex.hooks.json"
            if not cfg_src.is_file() or not hooks_src.is_file():
                raise FileNotFoundError("missing codex client templates under agent-kit/hooks/clients/")
            write_text(output_root / config_rel, cfg_src.read_text(encoding="utf-8"))
            write_json(output_root / hooks_rel, load_json(hooks_src))
        return
    # codex-native: skills only


def link_skill(src: Path, dst: Path, *, relative: bool = True) -> None:
    ensure_parent(dst)
    if dst.exists() or dst.is_symlink():
        if dst.is_symlink():
            dst.unlink()
        else:
            raise FileExistsError(f"refusing to replace non-symlink: {dst}")
    if relative:
        try:
            dst.symlink_to(os.path.relpath(src, start=dst.parent))
            return
        except ValueError:
            pass
    dst.symlink_to(src.resolve())


def copy_skill_tree(src: Path, dst: Path) -> None:
    ensure_parent(dst)
    if dst.exists() or dst.is_symlink():
        if dst.is_symlink() or dst.is_file():
            dst.unlink()
        elif dst.is_dir():
            shutil.rmtree(dst)
        else:
            raise FileExistsError(f"refusing to replace unsupported path: {dst}")
    shutil.copytree(src, dst)


def ensure_user_invoked_metadata(skill_dir: Path) -> None:
    """Mark a materialized skill as user-invoked without changing its body."""
    skill_md = skill_dir / "SKILL.md"
    text = skill_md.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        raise ValueError(f"{skill_dir.name}: SKILL.md is missing YAML frontmatter")
    end = text.find("\n---\n", 4)
    if end < 0:
        raise ValueError(f"{skill_dir.name}: SKILL.md has unterminated YAML frontmatter")
    frontmatter = text[4:end]
    if re.search(r"^disable-model-invocation\s*:", frontmatter, re.MULTILINE):
        frontmatter = re.sub(
            r"^disable-model-invocation\s*:.*$",
            "disable-model-invocation: true",
            frontmatter,
            count=1,
            flags=re.MULTILINE,
        )
    else:
        frontmatter = f"{frontmatter.rstrip()}\ndisable-model-invocation: true"
    skill_md.write_text(f"---\n{frontmatter}\n---\n{text[end + 5:]}", encoding="utf-8")


def set_skill_description(skill_dir: Path, description: str) -> None:
    """Replace the discovery description while preserving the maintained skill body."""
    skill_md = skill_dir / "SKILL.md"
    text = skill_md.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        raise ValueError(f"{skill_dir.name}: SKILL.md is missing YAML frontmatter")
    end = text.find("\n---\n", 4)
    if end < 0:
        raise ValueError(f"{skill_dir.name}: SKILL.md has unterminated YAML frontmatter")
    frontmatter = text[4:end]
    if not re.search(r"^description\s*:", frontmatter, re.MULTILINE):
        raise ValueError(f"{skill_dir.name}: SKILL.md frontmatter is missing description")
    frontmatter = re.sub(
        r"^description\s*:.*$",
        f"description: {description}",
        frontmatter,
        count=1,
        flags=re.MULTILINE,
    )
    skill_md.write_text(f"---\n{frontmatter}\n---\n{text[end + 5:]}", encoding="utf-8")


def install_external_skill(skill: dict[str, Any], dst: Path) -> None:
    source_type = str(skill.get("sourceType", ""))
    if source_type not in {"github", "git"}:
        raise ValueError(f"{skill.get('name')}: unsupported external skill sourceType {source_type!r}")

    source = str(skill["source"])
    ref = str(skill["ref"])
    rel_path = str(skill["path"])
    expected_hash = str(skill["computedHash"])

    with tempfile.TemporaryDirectory(prefix=f"agent-kit-{skill['name']}-") as tmp_name:
        repo_dir = Path(tmp_name) / "repo"
        subprocess.run(["git", "clone", "--quiet", source, str(repo_dir)], check=True)
        subprocess.run(
            ["git", "-c", "advice.detachedHead=false", "checkout", "--quiet", ref],
            cwd=repo_dir,
            check=True,
        )
        skill_dir = repo_dir / rel_path
        skill_md = skill_dir / "SKILL.md"
        if not skill_md.exists():
            raise ValueError(f"{skill['name']}: missing SKILL.md in external source {rel_path}")
        actual_hash = sha256_file(skill_md)
        if actual_hash != expected_hash:
            raise ValueError(
                f"{skill['name']}: SKILL.md hash mismatch; expected {expected_hash}, got {actual_hash}"
            )
        copy_skill_tree(skill_dir, dst)


def optional_plugin_targets(plugin: dict[str, Any], client: str, skills_dir: str) -> list[str]:
    client_cfg = plugin.get("clients", {}).get(client)
    if not isinstance(client_cfg, dict):
        raise ValueError(f"{plugin['name']}: unsupported client {client}")
    plugin_root = f"{client_cfg['plugins_dir']}/{plugin['name']}"
    targets = [plugin_root]
    manifest = str(client_cfg.get("manifest", ""))
    if manifest:
        targets.append(f"{plugin_root}/plugin.json")
    for asset in client_cfg.get("assets", []):
        targets.append(f"{plugin_root}/{asset}")
    plugin_skills = plugin.get("skills")
    if plugin_skills == "*":
        targets.append(f"{skills_dir}/*")
    elif isinstance(plugin_skills, list):
        targets.extend(f"{skills_dir}/{skill}" for skill in plugin_skills)
    return targets


def resolve_plugin_skills(
    plugin: dict[str, Any], plugin_root: Path
) -> list[tuple[str, Path]]:
    """Resolve which skills a plugin contributes, as (dst_basename, src_path) pairs."""
    name = str(plugin["name"])
    plugin_skills = plugin.get("skills")
    if plugin_skills == "*":
        requested_names: list[str] | None = None
    elif isinstance(plugin_skills, list):
        requested_names = [str(n) for n in plugin_skills]
    else:
        requested_names = []

    manifest_path = plugin_root / "plugin.json"
    declared_skills: list[str] | None = None
    if manifest_path.exists():
        try:
            plugin_manifest = json.loads(manifest_path.read_text())
        except json.JSONDecodeError as exc:
            raise ValueError(f"{name}: corrupt plugin.json: {exc}") from exc
        raw = plugin_manifest.get("skills")
        if isinstance(raw, list):
            declared_skills = [str(p) for p in raw]

    chosen: list[tuple[str, str]] = []
    if declared_skills is not None:
        by_basename: dict[str, str] = {}
        for raw_path in declared_skills:
            rel = os.path.normpath(raw_path).lstrip("/")
            if not rel:
                continue
            dst_name = rel.split("/")[-1]
            if dst_name in by_basename:
                raise ValueError(f"{name}: duplicate flattened skill name {dst_name!r}")
            by_basename[dst_name] = rel
        if requested_names is None:
            chosen = list(by_basename.items())
        else:
            for skill_name in requested_names:
                if skill_name not in by_basename:
                    raise ValueError(f"{name}: skill {skill_name!r} not declared in plugin.json")
                chosen.append((skill_name, by_basename[skill_name]))
    elif requested_names is None:
        chosen = [
            (p.name, f"skills/{p.name}")
            for p in sorted((plugin_root / "skills").iterdir())
            if (p / "SKILL.md").exists()
        ]
    elif requested_names:
        skill_root = plugin.get("skill_root")
        if not skill_root:
            raise ValueError(
                f"{name}: explicit 'skills' list requires a plugin.json 'skills' array "
                "or an explicit skill_root"
            )
        root = (plugin_root / str(skill_root)).resolve()
        if not root.is_relative_to(plugin_root.resolve()) or not root.is_dir():
            raise ValueError(f"{name}: invalid skill_root {skill_root!r}")
        candidates: dict[str, list[Path]] = {}
        for skill_md in root.rglob("SKILL.md"):
            candidates.setdefault(skill_md.parent.name, []).append(skill_md.parent)
        for skill_name in requested_names:
            matches = candidates.get(skill_name, [])
            if not matches:
                raise ValueError(f"{name}: missing allowlisted skill {skill_name!r} under {skill_root}")
            if len(matches) > 1:
                raise ValueError(f"{name}: ambiguous allowlisted skill {skill_name!r} under {skill_root}")
            chosen.append((skill_name, str(matches[0].relative_to(plugin_root.resolve()))))

    if not chosen:
        raise ValueError(f"{name}: no skills resolved (empty declaration or empty list)")

    plugin_root_resolved = plugin_root.resolve()
    resolved: list[tuple[str, Path]] = []
    for dst_name, src_rel in chosen:
        skill_src = (plugin_root / src_rel).resolve()
        if not skill_src.is_relative_to(plugin_root_resolved):
            raise ValueError(f"{name}: skill path escapes plugin root: {src_rel}")
        if not (skill_src / "SKILL.md").exists():
            raise ValueError(f"{name}: missing skill {src_rel}")
        resolved.append((dst_name, skill_src))
    return resolved


def install_resolved_skills(
    plugin_name: str,
    resolved: list[tuple[str, Path]],
    output_root: Path,
    skills_dir: str,
    occupied_skill_names: set[str],
) -> None:
    """Flat-copy resolved plugin skills into skills_dir with collision detection."""
    for dst_name, skill_src in resolved:
        if dst_name in occupied_skill_names:
            raise ValueError(
                f"{plugin_name}: skill name {dst_name!r} collides with an already-installed skill; "
                f"narrow optional-plugins.json 'skills' to exclude it or rename"
            )
        occupied_skill_names.add(dst_name)
        copy_skill_tree(skill_src, output_root / skills_dir / dst_name)


def install_optional_plugin(
    plugin: dict[str, Any],
    client: str,
    output_root: Path,
    skills_dir: str,
    occupied_skill_names: set[str],
) -> None:
    source_type = str(plugin.get("sourceType", ""))
    if source_type not in {"github", "git"}:
        raise ValueError(f"{plugin.get('name')}: unsupported optional plugin sourceType {source_type!r}")

    client_cfg = plugin.get("clients", {}).get(client)
    if not isinstance(client_cfg, dict):
        raise ValueError(f"{plugin['name']}: unsupported client {client}")

    source = str(plugin["source"])
    ref = str(plugin["ref"])
    rel_path = str(plugin["path"])
    plugin_root = output_root / str(client_cfg["plugins_dir"]) / str(plugin["name"])
    manifest = str(client_cfg["manifest"])

    with tempfile.TemporaryDirectory(prefix=f"agent-kit-plugin-{plugin['name']}-") as tmp_name:
        repo_dir = Path(tmp_name) / "repo"
        subprocess.run(["git", "clone", "--quiet", source, str(repo_dir)], check=True)
        subprocess.run(
            ["git", "-c", "advice.detachedHead=false", "checkout", "--quiet", ref],
            cwd=repo_dir,
            check=True,
        )
        src = repo_dir / rel_path
        if not src.exists():
            raise ValueError(f"{plugin['name']}: missing optional plugin source path {rel_path}")
        manifest_src = src / manifest
        if not manifest_src.exists():
            raise ValueError(f"{plugin['name']}: missing client plugin manifest {manifest}")
        for asset in client_cfg.get("assets", []):
            if not (src / str(asset)).exists():
                raise ValueError(f"{plugin['name']}: missing client plugin asset {asset}")
        if plugin_root.exists() or plugin_root.is_symlink():
            if plugin_root.is_symlink() or plugin_root.is_file():
                plugin_root.unlink()
            elif plugin_root.is_dir():
                shutil.rmtree(plugin_root)
            else:
                raise FileExistsError(f"refusing to replace unsupported path: {plugin_root}")
        ensure_parent(plugin_root)
        shutil.copytree(src, plugin_root, ignore=shutil.ignore_patterns(".git"))
        shutil.copy2(manifest_src, plugin_root / "plugin.json")

        install_resolved_skills(
            plugin["name"],
            resolve_plugin_skills(plugin, plugin_root),
            output_root,
            skills_dir,
            occupied_skill_names,
        )


def install_skill_library(
    library: dict[str, Any],
    output_root: Path,
    skills_dir: str,
    occupied_skill_names: set[str],
) -> list[str]:
    """Install only an allowlisted skill library; never copy plugin hooks/assets."""
    source_type = str(library.get("sourceType", ""))
    if source_type not in {"github", "git"}:
        raise ValueError(f"{library.get('name')}: unsupported library sourceType {source_type!r}")
    with tempfile.TemporaryDirectory(prefix=f"agent-kit-library-{library['name']}-") as tmp_name:
        repo_dir = Path(tmp_name) / "repo"
        subprocess.run(["git", "clone", "--quiet", str(library["source"]), str(repo_dir)], check=True)
        subprocess.run(
            ["git", "-c", "advice.detachedHead=false", "checkout", "--quiet", str(library["ref"])],
            cwd=repo_dir,
            check=True,
        )
        library_root = repo_dir / str(library["path"])
        if not library_root.is_dir():
            raise ValueError(f"{library['name']}: missing library source path {library['path']}")
        resolved = resolve_plugin_skills(library, library_root)
        install_resolved_skills(
            str(library["name"]),
            resolved,
            output_root,
            skills_dir,
            occupied_skill_names,
        )
        if library["name"] == "mattpocock-skills":
            for skill_name, _ in resolved:
                ensure_user_invoked_metadata(output_root / skills_dir / skill_name)
        if library["name"] == "superpowers":
            for skill_name, _ in resolved:
                set_skill_description(
                    output_root / skills_dir / skill_name,
                    CORE_SKILL_DESCRIPTIONS[skill_name],
                )
        return [name for name, _ in resolved]


def load_managed_state(output_root: Path) -> dict[str, Any]:
    state_path = output_root / ".harness" / "agent-profile-state.json"
    if not state_path.exists():
        return {"schema_version": 1, "clients": {}}
    try:
        state = load_json(state_path)
    except (json.JSONDecodeError, OSError) as exc:
        raise ValueError(f"managed profile state is invalid: {exc}") from exc
    if state.get("schema_version") != 1 or not isinstance(state.get("clients"), dict):
        raise ValueError("managed profile state has an unsupported schema")
    return state


def remove_stale_managed_skills(
    output_root: Path,
    skills_dir: str,
    previous: list[str],
    desired: set[str],
) -> list[str]:
    removed: list[str] = []
    for name in previous:
        if not re.fullmatch(r"[a-z0-9][a-z0-9-]*", name):
            raise ValueError(f"managed profile state contains invalid skill name {name!r}")
        if name in desired:
            continue
        target = output_root / skills_dir / name
        if target.is_symlink() or target.is_file():
            target.unlink()
        elif target.is_dir():
            shutil.rmtree(target)
        else:
            continue
        removed.append(name)
    return removed


def client_tree_is_declared_generated(output_root: Path, skills_dir: str) -> bool:
    """Treat a whole ignored client tree as installer-owned legacy output."""
    gitignore = output_root / ".gitignore"
    if not gitignore.is_file():
        return False
    client_root = skills_dir.split("/", 1)[0]
    rules = {
        line.strip()
        for line in gitignore.read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.lstrip().startswith("#")
    }
    return f"{client_root}/" in rules or client_root in rules


def install(
    client: str,
    profile: str,
    dry_run: bool,
    optional_plugin_names: list[str] | None = None,
    process_scaffold: str | None = None,
) -> dict[str, Any]:
    report = validate(profile)
    if report["errors"]:
        raise ValueError("; ".join(report["errors"]))

    manifest = load_json(MANIFEST_PATH)
    clients = manifest["clients"]
    if client not in clients:
        raise ValueError(f"unsupported client: {client}")
    client_cfg = clients[client]
    output_root = Path(os.environ.get("OUTPUT_ROOT", str(ROOT)))
    write_outputs = not dry_run or output_root != ROOT
    agent_profile, runtime_hash = prepare_agent_profile(
        output_root,
        client,
        write_outputs=write_outputs,
        process_scaffold=process_scaffold,
    )
    effective_profile = agent_profile["effective"]
    skills = report["skills"]
    external_skills = locked_external_skills(profile)
    explicit_optional_names = optional_plugin_names or []
    optional_plugins = locked_optional_plugins(explicit_optional_names)
    default_library_names: list[str] = []
    if effective_profile["sp_library"] == "enabled" and "superpowers" not in explicit_optional_names:
        default_library_names.append("superpowers")
    if effective_profile["matt_skills"] == "enabled" and "mattpocock-skills" not in explicit_optional_names:
        default_library_names.append("mattpocock-skills")
    libraries = locked_optional_plugins(default_library_names)
    commands = report["commands"]
    skills_root = local_skills_root()
    # Relative links are for in-repo installs; OUTPUT_ROOT temp trees may sit on
    # a different mount (macOS /var/folders vs workspace), so use absolute there.
    use_relative_links = output_root.resolve() == ROOT.resolve()

    targets: list[str] = []
    skills_dir = client_cfg["skills_dir"]
    generated_client_tree = client_tree_is_declared_generated(output_root, skills_dir)
    state = load_managed_state(output_root)
    previous_client_state = state.get("clients", {}).get(client, {})
    previously_managed_plugin_roots = set(previous_client_state.get("managed_plugin_roots", []))
    removed_managed_plugins: list[str] = []
    removed_legacy_bootstrap_skills: list[str] = []
    manual_cleanup_required: list[str] = []
    declarations = optional_plugin_declarations()
    for library_name in default_library_names:
        library_client = declarations[library_name].get("clients", {}).get(client, {})
        plugins_dir = library_client.get("plugins_dir")
        if not plugins_dir:
            continue
        rel = f"{plugins_dir}/{library_name}"
        legacy_root = output_root / rel
        if not (legacy_root.exists() or legacy_root.is_symlink()):
            continue
        if rel not in previously_managed_plugin_roots and not generated_client_tree:
            manual_cleanup_required.append(rel)
            continue
        if not dry_run:
            if legacy_root.is_symlink() or legacy_root.is_file():
                legacy_root.unlink()
            else:
                shutil.rmtree(legacy_root)
        removed_managed_plugins.append(rel)
    if removed_managed_plugins:
        for name in ("using-superpowers", "brainstorming", "writing-plans"):
            target = output_root / skills_dir / name
            if not (target.exists() or target.is_symlink()):
                continue
            if not dry_run:
                if target.is_symlink() or target.is_file():
                    target.unlink()
                else:
                    shutil.rmtree(target)
            removed_legacy_bootstrap_skills.append(name)
    if manual_cleanup_required:
        raise ValueError(
            "manual_cleanup_required: refusing to remove unowned legacy plugin paths: "
            + ", ".join(manual_cleanup_required)
        )

    occupied_skill_names: set[str] = set()
    for skill in skills:
        occupied_skill_names.add(skill)
        rel = f"{skills_dir}/{skill}"
        targets.append(rel)
        if write_outputs:
            link_skill(skills_root / skill, output_root / rel, relative=use_relative_links)

    for skill in external_skills:
        occupied_skill_names.add(skill["name"])
        rel = f"{skills_dir}/{skill['name']}"
        targets.append(rel)
        if write_outputs and not dry_run:
            install_external_skill(skill, output_root / rel)

    library_skill_names: dict[str, list[str]] = {}
    desired_library_skills: set[str] = set()
    planned_library_skills: set[str] = set()
    for library in libraries:
        declared = library.get("skills")
        if not isinstance(declared, list) or not declared:
            raise ValueError(f"{library['name']}: default library requires a non-empty skills allowlist")
        names = [str(name) for name in declared]
        library_skill_names[str(library["name"])] = names
        desired_library_skills.update(names)
        for name in names:
            if name in occupied_skill_names or name in planned_library_skills:
                raise ValueError(f"{library['name']}: library skill {name!r} collides with installed skills")
            planned_library_skills.add(name)
            targets.append(f"{skills_dir}/{name}")

    removed_managed_skills: list[str] = []
    previously_managed_library_skills = set(
        previous_client_state.get("managed_library_skills", [])
    )
    for name in desired_library_skills:
        target = output_root / skills_dir / name
        if (
            (target.exists() or target.is_symlink())
            and name not in previously_managed_library_skills
            and not (generated_client_tree and removed_managed_plugins)
        ):
            raise ValueError(
                f"manual_cleanup_required: refusing to overwrite unmanaged skill {target}"
            )
    if write_outputs and not dry_run:
        removed_managed_skills = remove_stale_managed_skills(
            output_root,
            skills_dir,
            list(previous_client_state.get("managed_library_skills", [])),
            desired_library_skills,
        )
        for library in libraries:
            installed_names = install_skill_library(
                library,
                output_root,
                skills_dir,
                occupied_skill_names,
            )
            if installed_names != library_skill_names[library["name"]]:
                raise ValueError(
                    f"{library['name']}: resolved skill order/content differs from configured allowlist"
                )

    optional_plugin_target_map = {
        plugin["name"]: optional_plugin_targets(plugin, client, client_cfg["skills_dir"])
        for plugin in optional_plugins
    }
    for plugin in optional_plugins:
        targets.extend(optional_plugin_target_map[plugin["name"]])
        if write_outputs and not dry_run:
            install_optional_plugin(
                plugin, client, output_root, client_cfg["skills_dir"], occupied_skill_names
            )

    commands_dir = client_cfg.get("commands_dir")
    if commands_dir:
        for command in commands:
            rel = f"{commands_dir}/{command}.md"
            targets.append(rel)
            if write_outputs:
                link_skill(
                    AGENT_KIT / "commands" / f"{command}.md",
                    output_root / rel,
                    relative=use_relative_links,
                )

    install_client_surface(
        client, client_cfg, output_root, targets, write_outputs=write_outputs
    )

    if write_outputs and not dry_run:
        state["runtime_hash"] = runtime_hash
        state.setdefault("clients", {})[client] = {
            "materialization": "agent-kit-install",
            "managed_skills": list(skills),
            "managed_library_skills": sorted(desired_library_skills),
            "library_skills": library_skill_names,
            "libraries": {
                "superpowers": effective_profile["sp_library"],
                "matt": effective_profile["matt_skills"],
            },
            "library_refs": {
                library["name"]: library["ref"]
                for library in libraries
            },
            "managed_plugin_roots": [
                f"{plugin['clients'][client]['plugins_dir']}/{plugin['name']}"
                for plugin in optional_plugins
            ],
        }
        write_json(output_root / ".harness" / "agent-profile-state.json", state)

    return {
        "client": client,
        "profile": profile,
        "dry_run": dry_run,
        "output_root": str(output_root),
        "targets": targets,
        "external_skills": [skill["name"] for skill in external_skills],
        "optional_plugins": [plugin["name"] for plugin in optional_plugins],
        "profile": agent_profile,
        "libraries": library_skill_names,
        "removed_managed_skills": removed_managed_skills,
        "removed_managed_plugins": removed_managed_plugins,
        "removed_legacy_bootstrap_skills": removed_legacy_bootstrap_skills,
        "manual_cleanup_required": manual_cleanup_required,
        "warnings": report["warnings"],
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="cmd", required=True)
    validate_parser = sub.add_parser("validate")
    validate_parser.add_argument("--profile", default=DEFAULT_PROFILE)
    install_parser = sub.add_parser("install")
    install_parser.add_argument("--client", required=True, choices=list(CLIENT_CHOICES))
    install_parser.add_argument("--profile", default=DEFAULT_PROFILE)
    install_parser.add_argument("--dry-run", action="store_true")
    install_parser.add_argument(
        "--process-scaffold",
        choices=["lean", "guided", "structured"],
        help="persist the profile advisory-density setting before install",
    )
    install_parser.add_argument("--with-optional-plugin", action="append", default=[])
    install_parser.add_argument(
        "--with-all-optional-plugins",
        action="store_true",
        help="opt into every declared optional plugin that supports the client",
    )
    args = parser.parse_args(argv)

    try:
        if args.cmd == "validate":
            payload = validate(args.profile)
        else:
            optional_names = list(args.with_optional_plugin)
            if args.with_all_optional_plugins:
                supported = [
                    n
                    for n, decl in optional_plugin_declarations().items()
                    if args.client in (decl.get("clients") or {})
                ]
                optional_names = sorted(set(optional_names) | set(supported))
            payload = install(
                args.client,
                args.profile,
                args.dry_run,
                optional_names,
                args.process_scaffold,
            )
    except Exception as exc:
        print(str(exc), file=sys.stderr)
        return 2
    print(json.dumps(payload, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
